FROM openjdk
VOLUME /tmp
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN sh ./export-credentials
RUN /app/gradlew bootJar
RUN mv /app/build/libs/*.jar /app/app.jar

CMD export JDBC_DATABASE_URL=$(cat tmp_url) && java -Dserver.port=$PORT $JAVA_OPTS -jar /app/app.jar