#!/bin/bash

full=$(heroku pg:credentials:url DATABASE_URL -a energy-calculator-be)
dbNameDirty="${full#*dbname=}"
dbName="${dbNameDirty% host*}"
hostDirty="${full#*host=}"
host="${hostDirty% port*}"
userDirty="${full#*user=}"
user="${userDirty% password*}"
passwordDirty="${full#*password=}"
password="${passwordDirty% sslmode*}"

"jdbc:postgresql://$host/$dbName" > /bin/tmp_url
$user > /bin/tmp_username
$password > /bin/tmp_password
