package pl.enactuspw.kompasbe.model

enum class ApartmentEquipment {
    WITHOUT_WATERWORKS_WATER_FROM_WELL,
    WATERWORKS_TOILET_WITHOUT_BATHROOM,
    WATERWORKS_SINK_WC_WITHOUT_BATHROOM_HOT_WATER,
    WATERWORKS_TOILET_BATHROOM_LOCAL_HOT_WATER,
    WATERWORKS_TOILET_BATHROOM_OUTSOURCED_HOT_WATER,
}